

CREATE TABLE HR.PRODUCTOS (
		ID_PRODUCTO NUMBER NOT NULL PRIMARY KEY,
		DESCRIPCION VARCHAR2(50) NOT NULL,
		PRECIO NUMBER DEFAULT 0  NOT NULL,
		STOCK NUMBER DEFAULT 0  NOT NULL
	);


INSERT INTO HR.PRODUCTOS 
(ID_PRODUCTO, DESCRIPCION, PRECIO, STOCK) 
VALUES (1, 'Televisión', 1522.8,5);

INSERT INTO HR.PRODUCTOS 
(ID_PRODUCTO, DESCRIPCION, PRECIO, STOCK) 
VALUES (2, 'Zapato', 122.2,5);
